package org.mymvc.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_id
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_name
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_phone
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    private Long userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.score
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.create_time
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_id
     *
     * @return the value of _user.user_id
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_id
     *
     * @param userId the value for _user.user_id
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_name
     *
     * @return the value of _user.user_name
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_name
     *
     * @param userName the value for _user.user_name
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_phone
     *
     * @return the value of _user.user_phone
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_phone
     *
     * @param userPhone the value for _user.user_phone
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.score
     *
     * @return the value of _user.score
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.score
     *
     * @param score the value for _user.score
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.create_time
     *
     * @return the value of _user.create_time
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.create_time
     *
     * @param createTime the value for _user.create_time
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}