package org.mymvc.dao;


import org.mymvc.model.User;


public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    void insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbggenerated Wed Nov 02 10:35:18 GMT+08:00 2016
     */
    int updateByPrimaryKey(User record);
}